
export default (len)=>{
    return `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Amet massa vitae tortor condimentum lacinia. Eu mi bibendum neque egestas. Integer vitae justo eget magna fermentum iaculis. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Lobortis mattis aliquam faucibus purus in. Magna eget est lorem ipsum dolor sit. Tempus urna et pharetra pharetra massa massa ultricies. Tellus in metus vulputate eu scelerisque. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Nunc pulvinar sapien et ligula. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Dui id ornare arcu odio ut sem nulla pharetra diam.

    Lectus nulla at volutpat diam ut venenatis tellus in metus. Diam maecenas sed enim ut. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Vitae semper quis lectus nulla at volutpat diam ut. Accumsan lacus vel facilisis volutpat est velit egestas. Vulputate dignissim suspendisse in est. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Augue mauris augue neque gravida. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Semper viverra nam libero justo laoreet sit. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. In hac habitasse platea dictumst quisque sagittis purus sit. Malesuada fames ac turpis egestas. Sem nulla pharetra diam sit. Dictum sit amet justo donec. Fusce ut placerat orci nulla pellentesque. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.
    
    Vitae elementum curabitur vitae nunc. Ultrices mi tempus imperdiet nulla. Gravida cum sociis natoque penatibus et magnis dis parturient. Orci nulla pellentesque dignissim enim sit amet venenatis. Fermentum et sollicitudin ac orci phasellus. Metus aliquam eleifend mi in nulla posuere sollicitudin. Odio ut enim blandit volutpat maecenas volutpat. A pellentesque sit amet porttitor. Sit amet cursus sit amet dictum. Mauris sit amet massa vitae tortor condimentum lacinia quis. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Rhoncus dolor purus non enim praesent elementum facilisis leo vel.
    
    Duis at tellus at urna condimentum mattis pellentesque id. Enim ut sem viverra aliquet eget sit amet. Aliquam ultrices sagittis orci a scelerisque purus semper. Eget nullam non nisi est sit. Nibh praesent tristique magna sit amet purus gravida quis blandit. Arcu vitae elementum curabitur vitae nunc sed velit. Nisl purus in mollis nunc sed. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Amet venenatis urna cursus eget. Vel pharetra vel turpis nunc. Non nisi est sit amet facilisis magna etiam tempor. Duis convallis convallis tellus id interdum. Ultrices in iaculis nunc sed augue. Lobortis feugiat vivamus at augue eget arcu dictum.
    
    Amet volutpat consequat mauris nunc. Sit amet mattis vulputate enim. Tristique nulla aliquet enim tortor. Egestas egestas fringilla phasellus faucibus. Pulvinar sapien et ligula ullamcorper malesuada proin. Feugiat vivamus at augue eget arcu dictum varius duis. Sit amet cursus sit amet dictum sit amet justo. Integer feugiat scelerisque varius morbi enim nunc. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Odio facilisis mauris sit amet massa. Risus viverra adipiscing at in tellus integer feugiat scelerisque.`.substring(0,len)
}
